# 基础配置
server:
  servlet:
    context-path: /scaffold
  port: 8080

# 日志配置
logging:
  level:
    com.wcx.scaffold.mapper: debug
  file: ./logs/scaffold.log

# 数据源配置
spring:
  datasource:
    url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
    username: chuck
    password: chuck
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: HospitalHikariCP
      max-lifetime: 60000
      connection-timeout: 30000

# mybatis 配置
mybatis:
  type-aliases-package: com.wcx.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 通用 Mapper 配置
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true

# PageHelper 配置
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: count=countSql